### ISSUE TITLE
`ggplot2` deprecated functions

### ISSUE THREAD

**Issue by auzaheta** [stocnet/goldfish#83]
**Maintenance**
`ggplot2` had deprecated `aes_string()` that we used to solve a note from the CMD check about "no visible binding for global variables". This affects the `examineOutliers()` and `examineChangepoints()` functions from diagnostics.R. 

This [vignette](https://ggplot2.tidyverse.org/articles/ggplot2-in-packages.html) explains the solution. `aes_string()` has been replaced following their suggestions. However, they also had some "best practices for common tasks" section where they suggested creating an `autoplot()` method for an S3 class. I would recommend the following changes for our case:

-  `examineOutliers()` and `examineChangepoints()` functions create a data object with the input needed for plotting. Their S3 class would be "goldfish.outlier" and "goldfish.changepoints".
- Create the corresponding `autoplot()` and `plot()` method as describe in the vignette.
- Create a `print()` method for the examine outputs. Content to be defined. 
- Create testing for functions. In particular, use vdiffr::[expect_doppelganger](https://vdiffr.r-lib.org/reference/expect_doppelganger.html) for the plotting. Only test those when local or in git actions. 

@jhollway, I'd be happy to read your input about it. It looks like a breaking change, but it would improve the usability of these functions. Also, if you have input on the printing format of the examine functions, it'd be helpful.

**Comment by jhollway** [comment]
@auzaheta, I have pushed some changes to develop that deal with the `aes_string()` issue, but indeed we could rethink how we manage these and other diagnostic functions for `{goldfish}`.
